### PR TITLE
New hero portraits

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR redesigns the hero portraits:

- It better fits the HOMM3 style
- Ranin has the same image than a hero from Courtyard
- At least a third can be retrieved in the Internet and are reused images

The new portraits have been made with Stable Diffusion and Gimp. This PR also fixes some mistakes in the translations.

### CODE REVIEW

**Comment by misiokles** [comment]
Please remove these big source pictures. Mod shouldn't contain unused files.

**Comment by Fabrice-TIERCELIN** [comment]
It's not source images. Source images are 512x512. It's images at the same format as here: https://github.com/vcmi-mods/courtyard/tree/vcmi-1.3/Courtyard/Content/sprites/courtyard/heroes/Audred

So do I remove it?

**Comment by misiokles** [comment]
Yeah, these courtyard files were uploaded by mistake :/

**Comment by Fabrice-TIERCELIN** [comment]
Removed. Here are the prompts:
* Amanda: _"Artistic drawing of a portrait of a medieval beautiful expressive young ginger woman, looking at the camera, in a magical atmosphere, with play of light"_
* Brooke: _"Photorealistic picture of a portrait of a white man knight, without helmet, with brown hair, looking at the camera, in a battle atmosphere, with play of light, in middle age"_
* Erika: _"Photorealistic picture of a portrait of a knight, with a helmet, looking at the camera, in a battle atmosphere, with play of light, in middle age"_
* Helena: _"Artistic picture of a portrait of a redhead beautiful young female warrior, slightly smiling, looking at the camera, in a castle, in a magical atmosphere, with play of light, in middle age"_
* Kasumi: _"Artistic picture of a portrait of a medieval gnoll knight, without helmet, looking at the camera, in a battle atmosphere, with play of light"_
* Nariko: _"Artistic drawing of a portrait of a beautiful expressive blond female knight, without helmet, looking back, in an epic atmosphere, with play of light, in middle age"_
* Noli: _"Artistic picture of a portrait of a blond male knight, without helmet, looking at the camera, in a battle atmosphere, with play of light, in middle age"_
* Patricia: _"Artistic picture of a portrait of a medieval redhead female, hunting, looking at the camera, in a dark atmosphere, with play of light"_
* Ranin: _"Artistic picture of a portrait of a medieval fat ginger bearded aristocrat man, looking at the camera, in a magical atmosphere, with play of light"_
* Salvirana: _"Photorealistic picture of a portrait of a male cleric, with a green hood, looking at the camera, in front view, in a dark atmosphere, with play of light, in middle age"_
* Stefan: _"Photorealistic picture of a portrait of a  blond male warrior, looking at the camera, in a dark atmosphere, with play of light, in middle age"_
* Susan: _"Artistic drawing of a portrait of a medieval young female priestess, with blue hair, looking at the camera, in a magical atmosphere, with play of light"_
* Sveneld: _"Photorealistic drawing of a portrait of a female young cleric woman, with a red hood, looking at the camera, in a magical atmosphere, with play of light, in middle age"_
* Tarinus: _"Artistic drawing of a portrait of a medieval young blond female priest, looking at the camera, in a magical atmosphere, with play of light"_
* Volh: _"Artistic drawing of a portrait of a medieval male vampire, with white hair, looking at the camera, in a magical atmosphere, with play of light"_
* Vseglas: _"Artistic drawing of a portrait of a medieval female elve, with black hair, with pointy ears, with pointed ears, looking at the camera, in a magical atmosphere, with play of light"_

**Comment by misiokles** [comment]
Can you make the same PR for vcmi-1.3 as well?

**Comment by Fabrice-TIERCELIN** [comment]
I can’t this week. You can do it vu checkouting vcmi1.3 branch,
cherry-picking my commit and pushing it.

Except if You haven’t the projects on your computer ☹️

You can fix the modtype of autoumn rampart yourself directly on git hub. Go
on the right branch, Go on the mod.json file, click on edit, change the
file and commit on the site.

Le lun. 24 juil. 2023 à 15:39, misiokles ***@***.***> a
écrit :

**Comment by misiokles** [comment]
Sure, I commit to 1.3 then in then in the evening.

**Pull request merged**
