### PR TITLE
Create a new town theme

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR changes the theme of the town. The music has been made with _Udio_ with the prompt `Classical music, Soundtrack, Gregorian chant, 160 bpm, Score, dynamic, allegro`.

### CODE REVIEW

**Comment by DjWarmonger** [comment]
Awesome! What a time to be alive :)

However, I think it has quite too much / too loud vocals compared to OH3 themes. But maybe that's only me.

**Comment by Fabrice-TIERCELIN** [comment]
I note your comment but I will rather create other themes instead of create a new one for Cathedral because there are too many themes to rework.

**Comment by Fabrice-TIERCELIN** [comment]
If you want, @DjWarmonger, you can create tracks on [Udio](https://www.udio.com/). You can start with the prompt `Classical music, Soundtrack, Gregorian chant, 160 bpm, Score, dynamic, allegro`. I select the _Manual Mode_ and _Instrumental_. I'm not sure I will have enough time to rescore all the themes: Udio is free till a week only.

**Comment by by003** [comment]
This music seems good! But what is the lyric of this chant?

**Comment by Fabrice-TIERCELIN** [comment]
I don't know. I haven't selected the lyrics so it's up to Udio.

@misiokles, @by003, @DjWarmonger, tell me if there is a mod in VCMI you want me to rescore

**Comment by by003** [comment]
@Fabrice-TIERCELIN I suggest that you can redo some details of these mods, like music, some graphs and balance works. I plan to remake some creature models, if you don't have more suitable ones please DON'T change these models.

**Pull request merged**
